name: ci

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Bump version
        run: |
          echo "1.0.0" > VERSION
          sed -i.bak "s/1.0.0/1.0.1/" VERSION
          cat VERSION
